name:  "RELEASE_R8_STORE_STORE_FENCE_CONSTRUCTOR_INLINING"
namespace:  "android_UNKNOWN"
description:  "feature flag for enabling more aggressive constructor inlining in R8"
workflow:  LAUNCH
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
