name:  "RELEASE_ZUMA_TARGET_ARCH_VARIANT_ARMV9"
namespace:  "android_UNKNOWN"
description:  "Build code for Tensor G3 (Zuma) as ARMv9-A instead of ARMv8.2-A"
workflow:  LAUNCH
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
